version: '3.8'
services:
  mongo:
    env_file:
      - ./docker-compose.env
    image: mongo:4
    ports:
      - 27017:27017

  mysql:
    env_file:
      - ./docker-compose.env
    image: mysql:8.0.23
    ports:
      - 3306:3306

  rabbit:
    env_file:
      - ./docker-compose.env
    hostname: minibank-rabbit
    image: rabbitmq:3.8.9-management
    ports:
      - 5672:5672
      - 15672:15672
